version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    #volumes:
      #- "./gateway:/var/www/app"
    ports:
      - "1321:1321"
    networks:
      - backend
      - frontend
  token:
    build: ./token
    restart: always
    hostname: token
    env_file:
      - .env
    #volumes:
      #- "./token:/var/www/app"
    networks:
      - backend
    links:
      - db
  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - .env
    #volumes:
    #  - "./user:/var/www/app"
    networks:
      - backend
    links:
      - db
  db:
    image: 'mongo'
    restart: always
    volumes:
      - "./db/data/db-files:/data/db"
    networks:
      - backend
    ports:
    - "27017:27017"
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge